-- 1) Создайте проект в Supabase.
-- 2) Откройте SQL Editor и выполните весь этот файл.
-- 3) Затем создайте администратора через Authentication → Users.
-- 4) Вставьте UUID созданного пользователя в INSERT ниже.

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_date date not null,
  start_time time not null,
  end_time time not null,
  start_at timestamptz not null,
  end_at timestamptz not null,
  type text not null check (type in ('open','closed')),
  movie_title text,
  description text,
  capacity integer not null default 0 check (capacity >= 0),
  organizer text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists bookings_date_idx on public.bookings(booking_date);
create index if not exists bookings_start_idx on public.bookings(start_at);
create index if not exists participants_booking_idx on public.participants(booking_id);

alter table public.bookings enable row level security;
alter table public.participants enable row level security;
alter table public.admins enable row level security;

-- Публичное расписание: читать можно всем.
drop policy if exists "public read bookings" on public.bookings;
create policy "public read bookings" on public.bookings
for select using (true);

drop policy if exists "public read participants" on public.participants;
create policy "public read participants" on public.participants
for select using (true);

-- Создавать бронирования и записываться на открытые сеансы могут все посетители.
drop policy if exists "public create bookings" on public.bookings;
create policy "public create bookings" on public.bookings
for insert with check (
  type in ('open','closed')
  and length(trim(organizer)) between 1 and 80
  and (type = 'closed' or (movie_title is not null and length(trim(movie_title)) > 0))
);

drop policy if exists "public create participants" on public.participants;
create policy "public create participants" on public.participants
for insert with check (length(trim(name)) between 1 and 80);

-- Удаление доступно только администраторам.
drop policy if exists "admins delete bookings" on public.bookings;
create policy "admins delete bookings" on public.bookings
for delete using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins delete participants" on public.participants;
create policy "admins delete participants" on public.participants
for delete using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admin read admins" on public.admins;
create policy "admin read admins" on public.admins
for select using (auth.uid() = user_id);

-- После создания пользователя-администратора замените UUID:
-- insert into public.admins(user_id) values ('00000000-0000-0000-0000-000000000000');

-- АВТОМАТИЧЕСКАЯ ОЧИСТКА
-- Сначала в Supabase Dashboard включите Integrations → Cron (pg_cron).
-- После этого выполните следующий блок.
--
-- Он запускает очистку каждый час. Записи удаляются через 24 часа после окончания,
-- а связанные participants удаляются автоматически благодаря ON DELETE CASCADE.
--
-- Если имя job уже существует, сначала удалите его в Dashboard → Integrations → Cron.

create or replace function public.cleanup_old_bookings()
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.bookings
  where end_at < now() - interval '24 hours';
$$;

revoke execute on function public.cleanup_old_bookings() from public;
revoke execute on function public.cleanup_old_bookings() from anon;
revoke execute on function public.cleanup_old_bookings() from authenticated;

-- Выполняется только планировщиком базы.
select cron.schedule(
  'cinema-cleanup-old-bookings',
  '0 * * * *',
  $$select public.cleanup_old_bookings()$$
)
where not exists (
  select 1 from cron.job where jobname = 'cinema-cleanup-old-bookings'
);
